title: "Warwick Allen's Theological Profile"
description: "A Molinist Arminian Baptist Charismatic with High Sacramental Convictions"
theme: jekyll-theme-cayman

# GitHub Pages specific settings
baseurl: "/essays"
url: "https://warwick-allen.github.io"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  syntax_highlighter: rouge

# Plugins (only those supported by GitHub Pages)
plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter

# Show excerpts on blog index
show_excerpts: false

